#!/bin/sh
MESSAGE=
if [ $# = 0 ]
then
  MESSAGE="Bump SpongeCommon."
else
  MESSAGE="Bump SpongeCommon $*"
fi
old_dir=`pwd`
cd `dirname $0`
cd SpongeForge
git add SpongeCommon
git commit -m "$MESSAGE"
git push
cd ../SpongeVanilla
git add SpongeCommon
git commit -m "$MESSAGE"
git push
cd $old_dir
