#!/bin/sh
git submodule foreach --recursive git fetch upstream

major=5
cd SpongeCommon
while git branch -r | grep upstream/stable-$major
do
  major=$((major + 1))
done
major=$((major - 1))
git checkout stable-$major
cd ..
cd SpongeForge
git checkout stable-$major
cd ..
cd SpongeVanilla
git checkout stable-$major
cd ..

cd SpongeCommon/SpongeAPI
minor=1
while git branch -r | grep upstream/stable-$major.$minor.0
do
  minor=$((minor + 1))
done
minor=$((minor - 1))
patch=1
while git branch -r | grep upstream/stable-$major.$minor.$patch
do
  patch=$((patch + 1))
done
patch=$((patch - 1))
git checkout stable-$major.$minor.$patch
cd ../..
git up
